### ISSUE TITLE
Rodent Traker show error when pressing "Analyze"

### ISSUE THREAD

**Issue by miguelconcham** [mathworks/Rodent-Tracker#1]
Dear kevinholly, 

thanks a lot for this amazing tool.

I am trying to run this in Matlab2022a, I am having some trouble when trying to analyses.
I followed the steps described in the instructions, but when pressing "Analyze" I get the following error, 

"Index in position 3 is invalid. Array indices must be positive integers or logical values.

Error in RodentTracker/AnalyzeButtonPushed (line 2913)
            imshow(app.Image(:,:,(size(app.Image_info,1)-1)),'Parent',app.Video_Window.RawAxes)

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn."

(I am not checking the boxes for saving any video)

do you have an idea of what could not be working?
When commenting this line, it throws error because do not recognize "bw_display_image" on the following lines.

thanks again, 

Miguel Concha-Miranda

**Comment by kevinholly** [comment]
Thanks for pointing this out. I updated the code to address this issue.
